class_name Quips
extends RefCounted
## Intro quips, shown two lines at a time like FNF's introText.txt.

const LIST := [
	["beep bop", "skee dah"],
	["blue balled", "again"],
	["the orang", "is watching"],
	["skill issue", "detected"],
	["downscroll", "superior"],
	["upscroll", "also fine"],
	["ghost tapping", "on"],
	["pico", "funny"],
	["made in godot", "not haxeflixel"],
	["ge proton", "is required"],
	["spooky month", "every month"],
	["week seven", "was worth the wait"],
	["boyfriend", "still cant talk"],
	["girlfriend", "sits on speakers professionally"],
	["monster", "did nothing wrong"],
	["ugh", "ugh"],
	["press enter", "you wont"],
	["lag train", "never stops"],
	["sick sick sick", "sick sick"],
	["full combo", "in your dreams"],
	["week six", "in pixels"],
	["senpai", "noticed you"],
	["dad", "disapproves"],
	["mom", "has a car"],
	["the speakers", "are load bearing"],
	["mic", "check one two"],
	["erect mode", "unlocked"],
	["ludum dare", "we remember"],
	["fnf soft", "very soft"],
	["psych engine", "goes brrr"],
	["botplay", "is cheating"],
	["eight keys", "no thank you"],
	["your keybinds", "are wrong"],
	["dfjk", "forever"],
	["trending", "on fnf twitter"],
	["the fnf idiots", "we love them"],
	["orang entertainment", "est today"],
	["note spam", "is not a chart"],
	["hit your notes", "or else"],
	["tankman", "ugh"],
	["bopeebo", "fresh"],
	["keep funkin", "always"],
	# Launcher stuff
	["achievement unlocked", "opened the launcher"],
	["the leaderboard", "remembers"],
	["the chart viewer", "sees all notes"],
	["press f6", "watch the notes"],
	["xbox 360", "blades are back"],
	["ps3", "trophy sound go"],
	["jim", "lives in the bin"],
	["compost", "says hi"],
	["the jukebox", "never sleeps"],
	["shuffle", "is a lifestyle"],
	["proton", "carries the team"],
	["linux gaming", "is real now"],
	["works on", "my steam deck"],
	["seven zip", "unzips everything"],
	["download queue", "doing its best"],
	["gamebanana", "art loading"],
	["one more mod", "then bed"],
	["rescan", "found nothing new"],
	["your library", "looks hungry"],
	["10 mods", "is a starter pack"],
	# FNF
	["hold notes", "hold on"],
	["the miss sound", "haunts me"],
	["sick", "not good"],
	["good", "not sick"],
	["shit rating", "says a lot"],
	["accuracy", "is a suggestion"],
	["combo broken", "heart broken"],
	["practice mode", "nobody saw that"],
	["the chart editor", "two am again"],
	["bpm change", "without warning"],
	["the speed", "was not necessary"],
	["fresh", "every time"],
	["story mode", "on hard"],
	["freeplay", "is home"],
	["the beat", "drops soon"],
	["vocals", "out of sync"],
	["one more try", "said 40 tries ago"],
	["the left arrow", "is the hardest one"],
	["perfect timing", "pure luck"],
	["rhythm", "is just math"],
	["nobody", "presses enter first try"],
	["funkin", "never ends"],
]


static func pick() -> Array:
	return LIST.pick_random()
